{
    'name': 'Craik & Comfort Website',
    'version': '1.0',
    'category': 'Website/Website',
    'summary': 'Premium bathroom design storefront for Craik & Comfort',
    'license': 'LGPL-3',
    'depends': [
        'website',
        'website_sale',
        'website_sale_stock',
    ],
    'data': [
        'data/website_data.xml',
        'data/unfreeze_core_records.xml',
        'data/unfreeze_besco_records.xml',
        'data/homepage_media.xml',
        'data/besco_media.xml',
        'data/banner_model.xml',
        'data/banner_views.xml',
        'data/banner_data.xml',
        'data/shop_nav_model.xml',
        'data/shop_nav_views.xml',
        'data/shop_nav_data.xml',
        'data/layout.xml',
        'data/homepage.xml',
        'data/homepage_page.xml',
        'data/product_display_fields.xml',
        'data/product_display_views.xml',
        'data/product_page.xml',
        'data/pages.xml',
        'data/extra_pages.xml',
        'data/service_pages.xml',
        'data/contact_page.xml',
        'data/shop_style.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'digitalx_website/static/src/js/dx_color_value_field.js',
            'digitalx_website/static/src/xml/dx_color_value_field.xml',
            'digitalx_website/static/src/scss/dx_color_value_field.scss',
        ],
        'web.assets_frontend': [
            'digitalx_website/static/src/js/dx_frontend.js',
            'digitalx_website/static/src/scss/dx_product.scss',
        ],
    },
    'author': "Salah Alhjany",
    'website': "https://saleh-alhajjani.odoo.com",
    'installable': True,
    'auto_install': False,
    'application': True,
}
